apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-hello
  template:
    metadata:
      labels:
        app: springboot-hello
    spec:
      containers:
        - name: springboot
          image: springboot-hello:v1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8088
